# Generated by Django 5.2.1 on 2025-06-04 09:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestRunReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_tests', models.IntegerField(default=0)),
                ('passed_tests', models.IntegerField(default=0)),
                ('failed_tests', models.IntegerField(default=0)),
                ('skipped_tests', models.IntegerField(default=0)),
                ('errors', models.IntegerField(default=0)),
                ('report_output', models.TextField(blank=True, null=True)),
                ('was_successful', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-run_at'],
            },
        ),
    ]
